# Exercice 1 : Manipulations de base

In [3]:
import numpy as np
a = np.arange(0,100,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [35]:
b = np.sin((a**2)*((np.pi)/2))
b

array([ 0.00000000e+00,  1.00000000e+00, -2.20436424e-15,  1.00000000e+00,
       -8.81745695e-15,  1.00000000e+00, -4.11555602e-14,  1.00000000e+00,
       -3.52698278e-14,  1.00000000e+00, -7.64253880e-14,  1.00000000e+00,
       -1.64622241e-13,  1.00000000e+00, -1.86173549e-13,  1.00000000e+00,
       -1.41079311e-13,  1.00000000e+00, -4.84086880e-13,  1.00000000e+00,
       -3.05701552e-13,  1.00000000e+00, -6.06706795e-14,  1.00000000e+00,
       -6.58488964e-13,  1.00000000e+00, -1.18966170e-12,  1.00000000e+00,
       -7.44694194e-13,  1.00000000e+00, -1.14257584e-12,  1.00000000e+00,
       -5.64317245e-13,  1.00000000e+00])

In [36]:
c = b.max()
c

1.0

In [37]:
d = sum(b == c)
d

17

In [42]:
e = len(np.argwhere(b == c))
e

17

# Exercice 2

In [4]:
diag = [[1,0,0],[0,1,0],[0,0,1]]
nodiag = [[5,4,3],[0,1,2],[6,7,8]]

def est_diagonale(m):
    return (m == np.triu(np.tril(m))).all()

print(est_diagonale(nodiag))
est_diagonale(diag)



False


True

In [6]:
triang = [[1,0,0],[0,1,0],[0,0,1]]
notriang = [[5,4,3],[0,1,2],[6,7,8]]

def est_triangulaire_sup(m):
    return (m == np.tril(m)).all()

print(est_triangulaire_sup(notriang))
est_triangulaire_sup(triang)

False


True

# Exercice 3

In [13]:
A = np.ones((8,8))
A[0:-1, 1:-1] = 0
A

array([[1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
A = [[1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1]]

B = [[1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1, 1, 1]]

C = np.concatenate((A, B), axis=0)
C

array([[1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [14]:
A = []
for i in range(0,8):
    A.append([0]*8)
    for j in range(0,8):
        if i>=7 or j==0 or j==7:
            A[i][j]=1
A

[[1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1]]

# Exercice 5

In [20]:
matrix=np.random.rand(50,50)

max = 0

for i in range(49):
    for j in range(49):
        if max < matrix[j+1][i]-matrix[i][j]:
            max = matrix[i][j]
print(max)

0.8209012220451325


# Exercice 4

In [15]:
import time 

tps1=time.time()
n=range(1000000)
sum(n)

tps2=time.time()-tps1

print(sum(n))
print(tps2)

499999500000
0.03895163536071777


In [18]:
tps1=time.time()

A=np.arange(0,1000000)
print(np.sum(A, dtype = np.int64))

tps2 = time.time()-tps1
print(tps2)

499999500000
0.0049896240234375


A priori la méthode avec Numpy est plus rapide !

# Exercice 6

In [36]:
A=np.random.rand(50,50)

print(np.sum(A<0.5))

1204


In [26]:
A[A < 0.5] = 0
A[A > 0.5] = 1
A

array([[1., 1., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 1., ..., 1., 0., 1.],
       [1., 1., 0., ..., 1., 0., 1.],
       [0., 1., 1., ..., 0., 0., 1.]])

# Exercice 7

In [37]:
np.matrix([[1, 2, 1, 1], [0, 1, 2, 1], [1, 0, 1, 2], [2, 1, 0, 1]])


matrix([[1, 2, 1, 1],
        [0, 1, 2, 1],
        [1, 0, 1, 2],
        [2, 1, 0, 1]])

In [38]:
a = np.array([[1, 2, 1, 1], [0, 1, 2, 1], [1, 0, 1, 2], [2, 1, 0, 1]])
b = np.array([0, 0, 1, 0])
x = np.linalg.solve(a, b)
x

array([-0.5,  0. , -0.5,  1. ])

In [39]:
a * b

array([[0, 0, 1, 0],
       [0, 0, 2, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

# Exercice 8

In [41]:
np.array([6, 4, 2, 1, 6, 4])

array([6, 4, 2, 1, 6, 4])